language: elixir
dist: bionic
elixir:
  - "1.10.3"
  - "1.11.2"
otp_release: 23.0
env:
  - PYTHON_VERSION=`which python2.7`
  - PYTHON_VERSION=`which python3.6`

addons:
  apt:
    packages:
      - libzmq3-dev
      - libsqlite3-dev

install:
  - pip install --user virtualenv
  - virtualenv -p $PYTHON_VERSION ~/test_ielixir
  - source ~/test_ielixir/bin/activate
  - pip install pip --upgrade
  - pip install tornado==4.5.3
  - pip install jupyter nose
before_script:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix deps.compile
  - git clone -b ielixir https://github.com/pprzetacznik/jupyter_kernel_test.git
  - MIX_ENV=dev ./install_script.sh
script:
  - mix test
  - cd jupyter_kernel_test
  - MIX_ENV=dev python test_ipython.py
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix docs
  - MIX_ENV=docs mix inch.report
  - MIX_ENV=test mix coveralls.travis
